// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/pelicula.proto

package pelicula

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AgregarPeliculaRequest struct {
	Nombre               string   `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Genero               string   `protobuf:"bytes,2,opt,name=genero,proto3" json:"genero,omitempty"`
	ActoresPrincipales   []string `protobuf:"bytes,3,rep,name=actores_principales,json=actoresPrincipales,proto3" json:"actores_principales,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgregarPeliculaRequest) Reset()         { *m = AgregarPeliculaRequest{} }
func (m *AgregarPeliculaRequest) String() string { return proto.CompactTextString(m) }
func (*AgregarPeliculaRequest) ProtoMessage()    {}
func (*AgregarPeliculaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcff8617f0633be, []int{0}
}

func (m *AgregarPeliculaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgregarPeliculaRequest.Unmarshal(m, b)
}
func (m *AgregarPeliculaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgregarPeliculaRequest.Marshal(b, m, deterministic)
}
func (m *AgregarPeliculaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgregarPeliculaRequest.Merge(m, src)
}
func (m *AgregarPeliculaRequest) XXX_Size() int {
	return xxx_messageInfo_AgregarPeliculaRequest.Size(m)
}
func (m *AgregarPeliculaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AgregarPeliculaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AgregarPeliculaRequest proto.InternalMessageInfo

func (m *AgregarPeliculaRequest) GetNombre() string {
	if m != nil {
		return m.Nombre
	}
	return ""
}

func (m *AgregarPeliculaRequest) GetGenero() string {
	if m != nil {
		return m.Genero
	}
	return ""
}

func (m *AgregarPeliculaRequest) GetActoresPrincipales() []string {
	if m != nil {
		return m.ActoresPrincipales
	}
	return nil
}

type AgregarPeliculaResponse struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre               string   `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Genero               string   `protobuf:"bytes,3,opt,name=genero,proto3" json:"genero,omitempty"`
	ActoresPrincipales   []string `protobuf:"bytes,4,rep,name=actores_principales,json=actoresPrincipales,proto3" json:"actores_principales,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgregarPeliculaResponse) Reset()         { *m = AgregarPeliculaResponse{} }
func (m *AgregarPeliculaResponse) String() string { return proto.CompactTextString(m) }
func (*AgregarPeliculaResponse) ProtoMessage()    {}
func (*AgregarPeliculaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcff8617f0633be, []int{1}
}

func (m *AgregarPeliculaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgregarPeliculaResponse.Unmarshal(m, b)
}
func (m *AgregarPeliculaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgregarPeliculaResponse.Marshal(b, m, deterministic)
}
func (m *AgregarPeliculaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgregarPeliculaResponse.Merge(m, src)
}
func (m *AgregarPeliculaResponse) XXX_Size() int {
	return xxx_messageInfo_AgregarPeliculaResponse.Size(m)
}
func (m *AgregarPeliculaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AgregarPeliculaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AgregarPeliculaResponse proto.InternalMessageInfo

func (m *AgregarPeliculaResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AgregarPeliculaResponse) GetNombre() string {
	if m != nil {
		return m.Nombre
	}
	return ""
}

func (m *AgregarPeliculaResponse) GetGenero() string {
	if m != nil {
		return m.Genero
	}
	return ""
}

func (m *AgregarPeliculaResponse) GetActoresPrincipales() []string {
	if m != nil {
		return m.ActoresPrincipales
	}
	return nil
}

type ObtenerPeliculaPorNombreRequest struct {
	Nombre               string   `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObtenerPeliculaPorNombreRequest) Reset()         { *m = ObtenerPeliculaPorNombreRequest{} }
func (m *ObtenerPeliculaPorNombreRequest) String() string { return proto.CompactTextString(m) }
func (*ObtenerPeliculaPorNombreRequest) ProtoMessage()    {}
func (*ObtenerPeliculaPorNombreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcff8617f0633be, []int{2}
}

func (m *ObtenerPeliculaPorNombreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObtenerPeliculaPorNombreRequest.Unmarshal(m, b)
}
func (m *ObtenerPeliculaPorNombreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObtenerPeliculaPorNombreRequest.Marshal(b, m, deterministic)
}
func (m *ObtenerPeliculaPorNombreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObtenerPeliculaPorNombreRequest.Merge(m, src)
}
func (m *ObtenerPeliculaPorNombreRequest) XXX_Size() int {
	return xxx_messageInfo_ObtenerPeliculaPorNombreRequest.Size(m)
}
func (m *ObtenerPeliculaPorNombreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObtenerPeliculaPorNombreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObtenerPeliculaPorNombreRequest proto.InternalMessageInfo

func (m *ObtenerPeliculaPorNombreRequest) GetNombre() string {
	if m != nil {
		return m.Nombre
	}
	return ""
}

type ObtenerPeliculaPorNombreResponse struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre               string   `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Genero               string   `protobuf:"bytes,3,opt,name=genero,proto3" json:"genero,omitempty"`
	ActoresPrincipales   []string `protobuf:"bytes,4,rep,name=actores_principales,json=actoresPrincipales,proto3" json:"actores_principales,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObtenerPeliculaPorNombreResponse) Reset()         { *m = ObtenerPeliculaPorNombreResponse{} }
func (m *ObtenerPeliculaPorNombreResponse) String() string { return proto.CompactTextString(m) }
func (*ObtenerPeliculaPorNombreResponse) ProtoMessage()    {}
func (*ObtenerPeliculaPorNombreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fcff8617f0633be, []int{3}
}

func (m *ObtenerPeliculaPorNombreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObtenerPeliculaPorNombreResponse.Unmarshal(m, b)
}
func (m *ObtenerPeliculaPorNombreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObtenerPeliculaPorNombreResponse.Marshal(b, m, deterministic)
}
func (m *ObtenerPeliculaPorNombreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObtenerPeliculaPorNombreResponse.Merge(m, src)
}
func (m *ObtenerPeliculaPorNombreResponse) XXX_Size() int {
	return xxx_messageInfo_ObtenerPeliculaPorNombreResponse.Size(m)
}
func (m *ObtenerPeliculaPorNombreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ObtenerPeliculaPorNombreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ObtenerPeliculaPorNombreResponse proto.InternalMessageInfo

func (m *ObtenerPeliculaPorNombreResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ObtenerPeliculaPorNombreResponse) GetNombre() string {
	if m != nil {
		return m.Nombre
	}
	return ""
}

func (m *ObtenerPeliculaPorNombreResponse) GetGenero() string {
	if m != nil {
		return m.Genero
	}
	return ""
}

func (m *ObtenerPeliculaPorNombreResponse) GetActoresPrincipales() []string {
	if m != nil {
		return m.ActoresPrincipales
	}
	return nil
}

func init() {
	proto.RegisterType((*AgregarPeliculaRequest)(nil), "pelicula.AgregarPeliculaRequest")
	proto.RegisterType((*AgregarPeliculaResponse)(nil), "pelicula.AgregarPeliculaResponse")
	proto.RegisterType((*ObtenerPeliculaPorNombreRequest)(nil), "pelicula.ObtenerPeliculaPorNombreRequest")
	proto.RegisterType((*ObtenerPeliculaPorNombreResponse)(nil), "pelicula.ObtenerPeliculaPorNombreResponse")
}

func init() { proto.RegisterFile("proto/pelicula.proto", fileDescriptor_1fcff8617f0633be) }

var fileDescriptor_1fcff8617f0633be = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x48, 0xcd, 0xc9, 0x4c, 0x2e, 0xcd, 0x49, 0xd4, 0x03, 0x73, 0x85, 0x38, 0x60,
	0x7c, 0xa5, 0x4a, 0x2e, 0x31, 0xc7, 0xf4, 0xa2, 0xd4, 0xf4, 0xc4, 0xa2, 0x00, 0xa8, 0x50, 0x50,
	0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x18, 0x17, 0x5b, 0x5e, 0x7e, 0x6e, 0x52, 0x51, 0xaa,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x94, 0x07, 0x12, 0x4f, 0x4f, 0xcd, 0x4b, 0x2d, 0xca,
	0x97, 0x60, 0x82, 0x88, 0x43, 0x78, 0x42, 0xfa, 0x5c, 0xc2, 0x89, 0xc9, 0x25, 0xf9, 0x45, 0xa9,
	0xc5, 0xf1, 0x05, 0x45, 0x99, 0x79, 0xc9, 0x99, 0x05, 0x89, 0x39, 0xa9, 0xc5, 0x12, 0xcc, 0x0a,
	0xcc, 0x1a, 0x9c, 0x41, 0x42, 0x50, 0xa9, 0x00, 0x84, 0x8c, 0x52, 0x17, 0x23, 0x97, 0x38, 0x86,
	0xdd, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x60, 0x8b, 0x79,
	0x83, 0x98, 0x32, 0x53, 0x90, 0x1c, 0xc3, 0x84, 0xc3, 0x31, 0xcc, 0xc4, 0x38, 0x86, 0x05, 0xa7,
	0x63, 0x2c, 0xb9, 0xe4, 0xfd, 0x93, 0x4a, 0x40, 0x9a, 0x61, 0x6e, 0x09, 0xc8, 0x2f, 0xf2, 0x03,
	0x5b, 0x42, 0x20, 0x40, 0x94, 0x26, 0x33, 0x72, 0x29, 0xe0, 0xd6, 0x3b, 0x40, 0x1e, 0x32, 0xba,
	0xc3, 0xc8, 0xc5, 0x0f, 0x73, 0x4e, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x50, 0x18, 0x17,
	0x3f, 0x5a, 0x80, 0x0b, 0x29, 0xe8, 0xc1, 0x93, 0x06, 0xf6, 0x74, 0x20, 0xa5, 0x88, 0x47, 0x05,
	0xd4, 0x73, 0x85, 0x5c, 0x12, 0xb8, 0x02, 0x40, 0x48, 0x13, 0xa1, 0x9d, 0x40, 0x00, 0x4b, 0x69,
	0x11, 0xa3, 0x14, 0x62, 0x65, 0x12, 0x1b, 0x38, 0x21, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x67, 0xbd, 0xa2, 0x51, 0xe0, 0x02, 0x00, 0x00,
}
